# Generated by Django 4.1.7 on 2023-04-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='role',
            field=models.CharField(blank=True, choices=[('farmer', 'Farmer'), ('customer', 'Customer')], max_length=255, null=True, verbose_name='Name'),
        ),
    ]
