# Generated by Django 4.1.7 on 2023-05-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_usermodel_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.CharField(blank=True, choices=[('farmer', 'Farmer'), ('customer', 'Customer')], max_length=255, null=True, verbose_name='Role'),
        ),
    ]
