# Generated by Django 4.1.7 on 2023-05-07 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nitrogen', models.IntegerField(blank=True, null=True, verbose_name='Nitrogen')),
                ('phosphorus', models.IntegerField(blank=True, null=True, verbose_name='Phosphorus')),
                ('potassium', models.IntegerField(blank=True, null=True, verbose_name='Potassium')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='Temperature')),
                ('humidity', models.FloatField(blank=True, null=True, verbose_name='Humidity')),
                ('ph', models.FloatField(blank=True, null=True, verbose_name='Ph Level')),
                ('rainfall', models.FloatField(blank=True, null=True, verbose_name='Rainfall Level')),
                ('result', models.TextField(blank=True, null=True, verbose_name='Result')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
